name: publish
on:
  push:
    branches:
      - preview
      - release

defaults:
  run:
    shell: bash

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml # use the callable ci job to run CI checks

  publish-update-bundle:
    if: github.head_ref == 'preview'
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v2

      - name: Publish EAS update
        uses: ./.github/actions/expo/update
        with:
          channel: 'preview'
          message: '${{ github.event.head_commit.message }}'
          expo_token: ${{ secrets.EXPO_TOKEN }}

  build-and-submit-android:
    # CI ideally *shouldn't* fail post-merge, but you could imagine criss-crossing PRs that break tests
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v2

      - name: ğŸ— Setup build environment
        uses: ./.github/actions/setup
        with:
          install_expo: true
          expo_token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸš€ Build Android app
        run: eas build --non-interactive --platform android --profile production --auto-submit

  build-and-submit-ios:
    # CI ideally *shouldn't* fail post-merge, but you could imagine criss-crossing PRs that break tests
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v2

      - name: ğŸ— Setup build environment
        uses: ./.github/actions/setup
        with:
          install_expo: true
          expo_token: ${{ secrets.EXPO_TOKEN }}

      - name: Replace IOS USER value in eas.json
        run: sed -i 's/$IOS_USER_ID/${{ secrets.IOS_USER_ID }}/g' eas.json

      - name: Replace IOS TEAM value in eas.json
        run: sed -i 's/$IOS_TEAM_ID/${{ secrets.IOS_TEAM_ID }}/g' eas.json

      - name: Replace IOS APP value in eas.json
        run: sed -i 's/$IOS_APP_ID/${{ secrets.IOS_APP_ID }}/g' eas.json

      - name: ğŸš€ Build iOS app
        run: eas build --non-interactive --platform ios --profile production --auto-submit
