name: publish
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml # use the callable ci job to run CI checks

  publish-update-bundle:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v2

      - name: Publish EAS update
        uses: ./.github/actions/expo/update
        with:
          channel: 'yulia-preview'
          message: '${{ github.event.head_commit.message }}'
          expo_token: ${{ secrets.EXPO_TOKEN }}

  build-android:
    if: ${{ false }} # disable iOS builds until we migrate to a different Expo tier

    # CI ideally *shouldn't* fail post-merge, but you could imagine criss-crossing PRs that break tests
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v2

      - name: ğŸ— Setup build environment
        uses: ./.github/actions/setup
        with:
          install_expo: true
          expo_token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸš€ Build Android app
        run: eas build --non-interactive --platform android --profile preview

  build-ios:
    # CI ideally *shouldn't* fail post-merge, but you could imagine criss-crossing PRs that break tests
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v2

      - name: ğŸ— Setup build environment
        uses: ./.github/actions/setup
        with:
          install_expo: true
          expo_token: ${{ secrets.EXPO_TOKEN }}
          
      - name: Replace USER value in eas.json
        run: sed -i 's/$USER/${{ secrets.APPLE_USER }}/g' eas.json

      - name: ğŸš€ Build iOS app
        run: eas build --non-interactive --platform ios --profile production --auto-submit
